version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cat-feeder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16zoofgf0cd7g"
s3_prefix = "cat-feeder"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

