AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cat-feeder

  Sample SAM Template for cat-feeder


Globals:
  Function:
    Timeout: 20
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        TABLE_NAME: !Ref CatFeederTable

Resources:
  FeedCatRestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CatFeeder
      Handler: com.catfeeder.handlers.FeedCatRest::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /feedcat
            Method: get
      Policies:
        - AWSIoTDataAccess
  CatEatingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CatFeeder
      Handler: com.catfeeder.handlers.CatEatingLambda::handleRequest
      Runtime: java11
      MemorySize: 512
      Policies: AmazonDynamoDBFullAccess
  CatFeederTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: CatFeeder
      TopicRulePayload:
        RuleDisabled: false
        Sql: SELECT * FROM 'catfeeder/#'
        Actions:
          - Lambda:
              FunctionArn: !GetAtt CatEatingFunction.Arn
  CatFeederTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timeStamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timeStamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FeedCatRestAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feedcat/"
  FeedCatRestFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FeedCatRestFunction.Arn
  FeedCatRestFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FeedCatRestFunctionRole.Arn
  CatEatingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CatEatingFunction.Arn
  CatEatingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CatEatingFunctionRole.Arn
